name: OKC Replicator for tekton files

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Target GitHub repository (e.g., org/abc-repo)'
        required: true
        type: string
      release_branch:
        description: 'Branch in target repo to merge PR into (e.g., rhoai-2.9)'
        required: true
        type: string
      version:
        description: 'New version identifier (e.g., v2.29.0)'
        required: true
        type: string
      okc_folder:
        description: 'Select folder inside OKC repo containing Tekton files'
        required: true
        type: choice
        options:
          - data-science-pipelines
          - odh-model-controller
          # Add all valid folder names here

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout OKC repository
        uses: actions/checkout@v4

      - name: Prepare Tekton files
        run: |
          repo_folder="${{ inputs.okc_folder }}"
          echo "Using OKC folder: $repo_folder"
          if [ ! -d "$repo_folder/.tekton" ]; then
            echo "ERROR: $repo_folder/.tekton does not exist!"
            exit 1
          fi
          mkdir -p extracted/.tekton
          cp -r "$repo_folder/.tekton/"* extracted/.tekton/
          echo "Replacing output-image tag with version: ${{ inputs.version }}"
          find extracted/.tekton/ -type f -name "*.yaml" | while read file; do
            sed -i -E '/name: output-image/{n; s|(value: .+:)[^[:space:]]+|\1'"${{ inputs.version }}"'|}' "$file"
          done
      - name: Create branch and commit updates
        run: |
          branch_name="tekton-update-${{ inputs.version }}"
          mkdir repo-workspace
          cd repo-workspace
          
          git init
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/opendatahub-io/kc-rep
          git fetch origin
          
          if git ls-remote --exit-code --heads origin "$branch_name" > /dev/null; then
            echo "Branch $branch_name exists remotely. Checking it out."
            git checkout -b "$branch_name" origin/"$branch_name"
          else
            echo "Branch $branch_name does not exist remotely. Creating new branch."
            git checkout -b "$branch_name"
          fi
          
          mkdir -p .tekton
          rsync -av --delete ../extracted/.tekton/ .tekton/
      
          echo "--- Git Status After Copy ---"
          git status
          echo "--- Git Diff After Copy ---"
          git diff
      
          if git diff --quiet; then
            echo "No changes detected. Exiting."
            exit 0
          fi
      
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .tekton
          git commit -m "Update Tekton output-image tags to version ${{ inputs.version }}"
          git push origin "$branch_name"



      - name: Create Pull Request
        env:
          REPO: ${{ inputs.repository }}
          BASE: ${{ inputs.release_branch }}
          HEAD: ${{ github.repository_owner }}:tekton-update-${{ inputs.version }}
          VERSION: ${{ inputs.version }}
          OKC_FOLDER: ${{ inputs.okc_folder }}
        run: |
          gh pr create \
            --repo "$REPO" \
            --base "$BASE" \
            --head "$HEAD" \
            --title "Update Tekton files to version $VERSION" \
            --body "This PR updates the \`output-image\` tags in \`$OKC_FOLDER/.tekton/\` to version \`$VERSION\`."
